import { Community, Member, Message } from "./types"

export const INITIAL_COMMUNITIES: Community[] = [
  {
    id: "general-discussion",
    name: "General Discussion",
    slug: "general-discussion",
    category: "General",
    description:
      "The central hub for all Vish Capitals investors. Share daily market thoughts, macro perspectives, and high-level ideas.",
    icon: "MessageSquare",
    avatarBg: "bg-[#0F2D1F]",
    iconColor: "text-[#D8E9DD]",
    memberCount: 4820,
    onlineCount: 412,
    unreadCount: 3,
    latestMessage: {
      text: "CPI print came in cooler than expected. Seeing strong volume in large caps.",
      senderName: "Marcus Vance",
      time: "10:42 AM",
    },
    rules: [
      {
        id: 1,
        title: "Respect and Civility",
        description: "Maintain a respectful, professional tone in all discussions.",
      },
      {
        id: 2,
        title: "No Financial Advice",
        description: "All commentary is for educational and sharing purposes only.",
      },
      {
        id: 3,
        title: "Quality Over Noise",
        description: "Share reasoned insights rather than spam or baseless hype.",
      },
    ],
    moderators: ["Vish Capitals Team", "Marcus Vance", "Elena Rostova"],
    isPinned: true,
  },
  {
    id: "investment-beginners",
    name: "Investment Beginners",
    slug: "investment-beginners",
    category: "Beginners",
    description:
      "A friendly, supportive space for newcomers to learn portfolio building, risk management basics, and market fundamentals.",
    icon: "GraduationCap",
    avatarBg: "bg-[#18794E]",
    iconColor: "text-white",
    memberCount: 2950,
    onlineCount: 189,
    unreadCount: 0,
    latestMessage: {
      text: "What is the best rule of thumb for position sizing on paper trades?",
      senderName: "Liam Chen",
      time: "09:15 AM",
    },
    rules: [
      {
        id: 1,
        title: "No Question is Too Basic",
        description: "Ask freely. This is a dedicated learning zone for all skill levels.",
      },
      {
        id: 2,
        title: "Constructive Guidance",
        description: "Experienced members should explain concepts patiently with context.",
      },
    ],
    moderators: ["Elena Rostova", "David Miller"],
  },
  {
    id: "stock-market",
    name: "Stock Market",
    slug: "stock-market",
    category: "Stocks",
    description:
      "Deep dives into global equities, sector rotations, earnings analysis, and balance sheet breakdowns.",
    icon: "TrendingUp",
    avatarBg: "bg-[#1B4D3E]",
    iconColor: "text-[#E8F2EA]",
    memberCount: 3640,
    onlineCount: 310,
    unreadCount: 5,
    latestMessage: {
      text: "NVDA and semiconductor complex retesting key Fibonacci expansion levels.",
      senderName: "Sarah Sterling",
      time: "10:38 AM",
    },
    rules: [
      {
        id: 1,
        title: "Back Claims with Data",
        description: "Include tickers, charts, or source citations whenever discussing valuation.",
      },
      {
        id: 2,
        title: "Earnings Etiquette",
        description: "Keep pre/post-earnings commentary focused on fundamental data.",
      },
    ],
    moderators: ["Sarah Sterling", "Alex Rivera"],
    isPinned: true,
  },
  {
    id: "crypto-discussion",
    name: "Crypto Discussion",
    slug: "crypto-discussion",
    category: "Crypto",
    description:
      "Bitcoin, Ethereum, layer-1 blockchains, on-chain liquidity metrics, and institutional crypto adoption.",
    icon: "Coins",
    avatarBg: "bg-[#255C48]",
    iconColor: "text-[#D5EAD7]",
    memberCount: 5120,
    onlineCount: 640,
    unreadCount: 2,
    latestMessage: {
      text: "BTC spot ETF net inflows hit $420M yesterday. Strong accumulation structure.",
      senderName: "Kavita Nair",
      time: "10:40 AM",
    },
    rules: [
      {
        id: 1,
        title: "No Meme Shilling",
        description: "Discussions must center around legitimate on-chain and market data.",
      },
      {
        id: 2,
        title: "Security Awareness",
        description: "Never share private keys, seed phrases, or external unverified links.",
      },
    ],
    moderators: ["Kavita Nair", "Vikram Patel"],
    isPinned: true,
  },
  {
    id: "market-news",
    name: "Market News",
    slug: "market-news",
    category: "News",
    description:
      "Real-time macroeconomic alerts, central bank policy announcements, geopolitical developments, and breaking updates.",
    icon: "Newspaper",
    avatarBg: "bg-[#2E473B]",
    iconColor: "text-[#FAF9F5]",
    memberCount: 6200,
    onlineCount: 780,
    unreadCount: 1,
    latestMessage: {
      text: "Federal Reserve minutes indicate data-dependent path for upcoming quarterly decision.",
      senderName: "Reuters Feed Bot",
      time: "10:12 AM",
    },
    rules: [
      {
        id: 1,
        title: "Verified Sources Only",
        description: "Post headlines only with reputable citations (Bloomberg, Reuters, SEC filings).",
      },
    ],
    moderators: ["NewsDesk Bot", "Vish Capitals Team"],
  },
  {
    id: "trading-strategies",
    name: "Trading Strategies",
    slug: "trading-strategies",
    category: "Strategies",
    description:
      "Systematic backtesting, algorithmic workflows, breakout setups, options Greeks, and risk mitigation models.",
    icon: "Sparkles",
    avatarBg: "bg-[#163D2F]",
    iconColor: "text-[#A8D2B5]",
    memberCount: 2840,
    onlineCount: 245,
    unreadCount: 0,
    latestMessage: {
      text: "Sharing a Mean-Reversion setup on the 4H timeframe with strict 1:2.5 risk-to-reward.",
      senderName: "Dr. Henrik Lind",
      time: "08:50 AM",
    },
    rules: [
      {
        id: 1,
        title: "Include Stop-Loss Guidelines",
        description: "Always outline risk parameters when sharing technical setups.",
      },
    ],
    moderators: ["Dr. Henrik Lind", "Sarah Sterling"],
  },
  {
    id: "portfolio-discussion",
    name: "Portfolio Discussion",
    slug: "portfolio-discussion",
    category: "Portfolio",
    description:
      "Asset allocation models, modern portfolio theory, Sharpe ratio optimization, and long-term wealth preservation.",
    icon: "PieChart",
    avatarBg: "bg-[#1E4D3B]",
    iconColor: "text-[#BFE3CB]",
    memberCount: 3100,
    onlineCount: 204,
    unreadCount: 0,
    latestMessage: {
      text: "How are people balancing international exposure against US large-cap tech right now?",
      senderName: "Maya Lin",
      time: "Yesterday",
    },
    rules: [
      {
        id: 1,
        title: "Confidentiality",
        description: "Do not disclose private financial account identifiers or sensitive balances.",
      },
    ],
    moderators: ["Maya Lin", "Vish Capitals Team"],
  },
]

export const INITIAL_MEMBERS: Record<string, Member[]> = {
  "general-discussion": [
    {
      id: "u1",
      name: "Marcus Vance",
      handle: "@mvance_macro",
      avatar: "MV",
      role: "Pro Analyst",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#18794E]",
      joinedDate: "Jan 2025",
    },
    {
      id: "u2",
      name: "Elena Rostova",
      handle: "@elena_quant",
      avatar: "ER",
      role: "Moderator",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#0F2D1F]",
      joinedDate: "Feb 2025",
    },
    {
      id: "u3",
      name: "Sarah Sterling",
      handle: "@sterling_equities",
      avatar: "SS",
      role: "Top Contributor",
      isOnline: true,
      badgeColor: "bg-[#F3F0E5] text-[#55554E]",
      joinedDate: "Mar 2025",
    },
    {
      id: "u4",
      name: "David Miller",
      handle: "@dmiller_trades",
      avatar: "DM",
      role: "Member",
      isOnline: false,
      joinedDate: "Jun 2025",
    },
    {
      id: "u5",
      name: "Kavita Nair",
      handle: "@kavita_crypto",
      avatar: "KN",
      role: "Pro Analyst",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#18794E]",
      joinedDate: "Nov 2024",
    },
    {
      id: "u_self",
      name: "Vish Sai",
      handle: "@vish_capitals",
      avatar: "VS",
      role: "Admin",
      isOnline: true,
      badgeColor: "bg-[#0F2D1F] text-white",
      joinedDate: "Founder",
    },
  ],
  "crypto-discussion": [
    {
      id: "u5",
      name: "Kavita Nair",
      handle: "@kavita_crypto",
      avatar: "KN",
      role: "Pro Analyst",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#18794E]",
      joinedDate: "Nov 2024",
    },
    {
      id: "u6",
      name: "Vikram Patel",
      handle: "@vikram_onchain",
      avatar: "VP",
      role: "Moderator",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#0F2D1F]",
      joinedDate: "Dec 2024",
    },
    {
      id: "u7",
      name: "Zack Thorne",
      handle: "@zack_defi",
      avatar: "ZT",
      role: "Member",
      isOnline: false,
      joinedDate: "Jan 2026",
    },
    {
      id: "u_self",
      name: "Vish Sai",
      handle: "@vish_capitals",
      avatar: "VS",
      role: "Admin",
      isOnline: true,
      badgeColor: "bg-[#0F2D1F] text-white",
      joinedDate: "Founder",
    },
  ],
  "stock-market": [
    {
      id: "u3",
      name: "Sarah Sterling",
      handle: "@sterling_equities",
      avatar: "SS",
      role: "Pro Analyst",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#18794E]",
      joinedDate: "Mar 2025",
    },
    {
      id: "u8",
      name: "Alex Rivera",
      handle: "@arivera_sec",
      avatar: "AR",
      role: "Moderator",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#0F2D1F]",
      joinedDate: "Apr 2025",
    },
    {
      id: "u_self",
      name: "Vish Sai",
      handle: "@vish_capitals",
      avatar: "VS",
      role: "Admin",
      isOnline: true,
      badgeColor: "bg-[#0F2D1F] text-white",
      joinedDate: "Founder",
    },
  ],
}

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  "general-discussion": [
    {
      id: "m1",
      communityId: "general-discussion",
      senderId: "u2",
      senderName: "Elena Rostova",
      senderAvatar: "ER",
      senderRole: "Moderator",
      content:
        "Welcome everyone to today's Vish Capitals session. Remember that market breadth has been broadening out nicely beyond mega-caps this week.",
      timestamp: "09:30 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [
        { emoji: "📈", count: 14, hasReacted: true },
        { emoji: "👍", count: 8, hasReacted: false },
      ],
      isPinned: true,
    },
    {
      id: "m2",
      communityId: "general-discussion",
      senderId: "u3",
      senderName: "Sarah Sterling",
      senderAvatar: "SS",
      senderRole: "Top Contributor",
      content:
        "Watching $NVDA and $MSFT support levels ahead of the next FOMC statement. The 20-day EMA has provided firm support on every pullback so far.",
      timestamp: "10:15 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [
        { emoji: "🎯", count: 6, hasReacted: false },
        { emoji: "🔥", count: 9, hasReacted: true },
      ],
    },
    {
      id: "m3",
      communityId: "general-discussion",
      senderId: "u1",
      senderName: "Marcus Vance",
      senderAvatar: "MV",
      senderRole: "Pro Analyst",
      content:
        "CPI print came in cooler than expected. Seeing strong volume in large caps across both NYSE and Nasdaq. Friday AI score updated to 87/100 constructive momentum.",
      timestamp: "10:42 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [
        { emoji: "🚀", count: 18, hasReacted: false },
        { emoji: "⚡", count: 7, hasReacted: true },
      ],
      attachments: [
        {
          type: "chart",
          title: "Market Breadth & AI Confidence",
          subtitle: "Friday AI Signal: Strong Risk Regime (87/100)",
        },
      ],
    },
    {
      id: "m4",
      communityId: "general-discussion",
      senderId: "u_self",
      senderName: "Vish Sai (You)",
      senderAvatar: "VS",
      senderRole: "Admin",
      content:
        "Great observation Marcus. Our risk models have adjusted cash reserves from 8% to 5% accordingly to capture the trend while trailing stop-losses remain tight.",
      timestamp: "10:44 AM",
      date: "Today",
      isCurrentUser: true,
      reactions: [
        { emoji: "👏", count: 12, hasReacted: false },
        { emoji: "🤝", count: 5, hasReacted: false },
      ],
    },
  ],
  "crypto-discussion": [
    {
      id: "c1",
      communityId: "crypto-discussion",
      senderId: "u6",
      senderName: "Vikram Patel",
      senderAvatar: "VP",
      senderRole: "Moderator",
      content:
        "$BTC holding firmly above key support around $111,800. On-chain exchange balances are at multi-year lows indicating strong holder conviction.",
      timestamp: "09:45 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [
        { emoji: "🔥", count: 22, hasReacted: true },
        { emoji: "🚀", count: 15, hasReacted: false },
      ],
    },
    {
      id: "c2",
      communityId: "crypto-discussion",
      senderId: "u5",
      senderName: "Kavita Nair",
      senderAvatar: "KN",
      senderRole: "Pro Analyst",
      content:
        "BTC spot ETF net inflows hit $420M yesterday. Strong accumulation structure. $SOL also showing relative strength with +3.1% outperformance.",
      timestamp: "10:40 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [
        { emoji: "📈", count: 19, hasReacted: true },
        { emoji: "💎", count: 11, hasReacted: false },
      ],
      attachments: [
        {
          type: "chart",
          title: "BTC / USD 4H Liquidity Heatmap",
          subtitle: "Clear liquidity pool target at $118,500",
        },
      ],
    },
    {
      id: "c3",
      communityId: "crypto-discussion",
      senderId: "u_self",
      senderName: "Vish Sai (You)",
      senderAvatar: "VS",
      senderRole: "Admin",
      content:
        "Remember to manage leverage sensibly around the weekly close. The paper trading terminal has updated live orderbook liquidity for testing setups.",
      timestamp: "10:43 AM",
      date: "Today",
      isCurrentUser: true,
      reactions: [{ emoji: "🛡️", count: 8, hasReacted: false }],
    },
  ],
  "stock-market": [
    {
      id: "s1",
      communityId: "stock-market",
      senderId: "u8",
      senderName: "Alex Rivera",
      senderAvatar: "AR",
      senderRole: "Moderator",
      content:
        "Q3 earnings consensus is being revised upwards across enterprise cloud providers. Free cash flow yields remain attractive.",
      timestamp: "08:30 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [{ emoji: "📊", count: 11, hasReacted: false }],
    },
    {
      id: "s2",
      communityId: "stock-market",
      senderId: "u3",
      senderName: "Sarah Sterling",
      senderAvatar: "SS",
      senderRole: "Top Contributor",
      content:
        "NVDA and semiconductor complex retesting key Fibonacci expansion levels. Volume profile shows strong acceptance at current price bands.",
      timestamp: "10:38 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [
        { emoji: "🚀", count: 14, hasReacted: true },
        { emoji: "💡", count: 6, hasReacted: false },
      ],
    },
  ],
  "investment-beginners": [
    {
      id: "b1",
      communityId: "investment-beginners",
      senderId: "u2",
      senderName: "Elena Rostova",
      senderAvatar: "ER",
      senderRole: "Moderator",
      content:
        "Quick reminder for new investors: Paper Trading allows you to rehearse every strategy with zero capital risk before executing real orders.",
      timestamp: "08:15 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [
        { emoji: "🎓", count: 28, hasReacted: true },
        { emoji: "⭐", count: 12, hasReacted: false },
      ],
    },
    {
      id: "b2",
      communityId: "investment-beginners",
      senderId: "u4",
      senderName: "Liam Chen",
      senderAvatar: "LC",
      senderRole: "Member",
      content:
        "What is the best rule of thumb for position sizing on paper trades? Should I cap each trade at 2% total portfolio risk?",
      timestamp: "09:15 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [{ emoji: "🙋", count: 7, hasReacted: false }],
    },
    {
      id: "b3",
      communityId: "investment-beginners",
      senderId: "u_self",
      senderName: "Vish Sai (You)",
      senderAvatar: "VS",
      senderRole: "Admin",
      content:
        "Exactly, Liam! The 1-2% risk-per-trade rule is the gold standard used by institutional prop desks. It protects you against string losses and lets compounding work.",
      timestamp: "09:22 AM",
      date: "Today",
      isCurrentUser: true,
      reactions: [
        { emoji: "🎯", count: 15, hasReacted: true },
        { emoji: "🙏", count: 9, hasReacted: false },
      ],
    },
  ],
  "market-news": [
    {
      id: "n1",
      communityId: "market-news",
      senderId: "u_bot",
      senderName: "Reuters Feed Bot",
      senderAvatar: "RB",
      senderRole: "Moderator",
      content:
        "Federal Reserve minutes indicate data-dependent path for upcoming quarterly decision. Treasury 10-year yield consolidates at 4.18%.",
      timestamp: "10:12 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [{ emoji: "📰", count: 32, hasReacted: false }],
    },
  ],
  "trading-strategies": [
    {
      id: "t1",
      communityId: "trading-strategies",
      senderId: "u9",
      senderName: "Dr. Henrik Lind",
      senderAvatar: "HL",
      senderRole: "Pro Analyst",
      content:
        "Sharing a Mean-Reversion setup on the 4H timeframe with strict 1:2.5 risk-to-reward. Combining Bollinger Band squeezes with RSI divergence.",
      timestamp: "08:50 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [
        { emoji: "🧠", count: 17, hasReacted: true },
        { emoji: "📈", count: 12, hasReacted: false },
      ],
    },
  ],
  "portfolio-discussion": [
    {
      id: "p1",
      communityId: "portfolio-discussion",
      senderId: "u10",
      senderName: "Maya Lin",
      senderAvatar: "ML",
      senderRole: "Moderator",
      content:
        "How are people balancing international exposure against US large-cap tech right now? We are maintaining a 65/25/10 domestic/global/liquid cash split.",
      timestamp: "Yesterday",
      date: "Yesterday",
      isCurrentUser: false,
      reactions: [{ emoji: "💼", count: 14, hasReacted: false }],
    },
  ],
}
