import { Community, Member, Message } from "./types"

export const INITIAL_COMMUNITIES: Community[] = [
  {
    id: "general-discussion",
    name: "General Discussion",
    slug: "general-discussion",
    category: "General",
    description:
      "The central hub for all Vish Capitals investors. Share daily market thoughts, macro perspectives, and high-level ideas.",
    icon: "MessageSquare",
    avatarBg: "bg-[#0F2D1F]",
    iconColor: "text-[#D8E9DD]",
    memberCount: 4820,
    onlineCount: 412,
    unreadCount: 0,
    latestMessage: {
      text: "Welcome to the official General Discussion channel. Share your market analysis and ideas below.",
      senderName: "Elena Rostova",
      time: "Today",
    },
    rules: [
      {
        id: 1,
        title: "Respect and Civility",
        description: "Maintain a respectful, professional tone in all discussions.",
      },
      {
        id: 2,
        title: "No Financial Advice",
        description: "All commentary is for educational and sharing purposes only.",
      },
      {
        id: 3,
        title: "Quality Over Noise",
        description: "Share reasoned insights rather than spam or baseless hype.",
      },
    ],
    moderators: ["Vish Capitals Team", "Marcus Vance", "Elena Rostova"],
    isPinned: true,
  },
  {
    id: "investment-beginners",
    name: "Investment Beginners",
    slug: "investment-beginners",
    category: "Beginners",
    description:
      "A friendly, supportive space for newcomers to learn portfolio building, risk management basics, and market fundamentals.",
    icon: "GraduationCap",
    avatarBg: "bg-[#18794E]",
    iconColor: "text-white",
    memberCount: 2950,
    onlineCount: 189,
    unreadCount: 0,
    latestMessage: {
      text: "Welcome to Beginners Hub! Feel free to ask any question regarding paper trading or risk rules.",
      senderName: "Elena Rostova",
      time: "Today",
    },
    rules: [
      {
        id: 1,
        title: "No Question is Too Basic",
        description: "Ask freely. This is a dedicated learning zone for all skill levels.",
      },
      {
        id: 2,
        title: "Constructive Guidance",
        description: "Experienced members should explain concepts patiently with context.",
      },
    ],
    moderators: ["Elena Rostova", "David Miller"],
  },
  {
    id: "stock-market",
    name: "Stock Market",
    slug: "stock-market",
    category: "Stocks",
    description:
      "Deep dives into global equities, sector rotations, earnings analysis, and balance sheet breakdowns.",
    icon: "TrendingUp",
    avatarBg: "bg-[#1B4D3E]",
    iconColor: "text-[#E8F2EA]",
    memberCount: 3640,
    onlineCount: 310,
    unreadCount: 0,
    latestMessage: {
      text: "Official Equities & Stocks discussion channel is open. Post your ticker setups here.",
      senderName: "Alex Rivera",
      time: "Today",
    },
    rules: [
      {
        id: 1,
        title: "Back Claims with Data",
        description: "Include tickers, charts, or source citations whenever discussing valuation.",
      },
      {
        id: 2,
        title: "Earnings Etiquette",
        description: "Keep pre/post-earnings commentary focused on fundamental data.",
      },
    ],
    moderators: ["Sarah Sterling", "Alex Rivera"],
    isPinned: true,
  },
  {
    id: "crypto-discussion",
    name: "Crypto Discussion",
    slug: "crypto-discussion",
    category: "Crypto",
    description:
      "Bitcoin, Ethereum, layer-1 blockchains, on-chain liquidity metrics, and institutional crypto adoption.",
    icon: "Coins",
    avatarBg: "bg-[#255C48]",
    iconColor: "text-[#D5EAD7]",
    memberCount: 5120,
    onlineCount: 640,
    unreadCount: 0,
    latestMessage: {
      text: "Crypto channel is active. Discuss on-chain data, BTC, ETH, and layer-1 developments.",
      senderName: "Vikram Patel",
      time: "Today",
    },
    rules: [
      {
        id: 1,
        title: "No Meme Shilling",
        description: "Discussions must center around legitimate on-chain and market data.",
      },
      {
        id: 2,
        title: "Security Awareness",
        description: "Never share private keys, seed phrases, or external unverified links.",
      },
    ],
    moderators: ["Kavita Nair", "Vikram Patel"],
    isPinned: true,
  },
  {
    id: "market-news",
    name: "Market News",
    slug: "market-news",
    category: "News",
    description:
      "Real-time macroeconomic alerts, central bank policy announcements, geopolitical developments, and breaking updates.",
    icon: "Newspaper",
    avatarBg: "bg-[#2E473B]",
    iconColor: "text-[#FAF9F5]",
    memberCount: 6200,
    onlineCount: 780,
    unreadCount: 0,
    latestMessage: {
      text: "Real-time macroeconomic and market headlines desk.",
      senderName: "NewsDesk Bot",
      time: "Today",
    },
    rules: [
      {
        id: 1,
        title: "Verified Sources Only",
        description: "Post headlines only with reputable citations (Bloomberg, Reuters, SEC filings).",
      },
    ],
    moderators: ["NewsDesk Bot", "Vish Capitals Team"],
  },
  {
    id: "trading-strategies",
    name: "Trading Strategies",
    slug: "trading-strategies",
    category: "Strategies",
    description:
      "Systematic backtesting, algorithmic workflows, breakout setups, options Greeks, and risk mitigation models.",
    icon: "Sparkles",
    avatarBg: "bg-[#163D2F]",
    iconColor: "text-[#A8D2B5]",
    memberCount: 2840,
    onlineCount: 245,
    unreadCount: 0,
    latestMessage: {
      text: "Post systematic trading setups, backtest ideas, and risk mitigation models.",
      senderName: "Dr. Henrik Lind",
      time: "Today",
    },
    rules: [
      {
        id: 1,
        title: "Include Stop-Loss Guidelines",
        description: "Always outline risk parameters when sharing technical setups.",
      },
    ],
    moderators: ["Dr. Henrik Lind", "Sarah Sterling"],
  },
  {
    id: "portfolio-discussion",
    name: "Portfolio Discussion",
    slug: "portfolio-discussion",
    category: "Portfolio",
    description:
      "Asset allocation models, modern portfolio theory, Sharpe ratio optimization, and long-term wealth preservation.",
    icon: "PieChart",
    avatarBg: "bg-[#1E4D3B]",
    iconColor: "text-[#BFE3CB]",
    memberCount: 3100,
    onlineCount: 204,
    unreadCount: 0,
    latestMessage: {
      text: "Share asset allocation frameworks, rebalancing strategies, and diversification models.",
      senderName: "Maya Lin",
      time: "Today",
    },
    rules: [
      {
        id: 1,
        title: "Confidentiality",
        description: "Do not disclose private financial account identifiers or sensitive balances.",
      },
    ],
    moderators: ["Maya Lin", "Vish Capitals Team"],
  },
]

export const INITIAL_MEMBERS: Record<string, Member[]> = {
  "general-discussion": [
    {
      id: "u1",
      name: "Marcus Vance",
      handle: "@mvance_macro",
      avatar: "MV",
      role: "Pro Analyst",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#18794E]",
      joinedDate: "Jan 2025",
    },
    {
      id: "u2",
      name: "Elena Rostova",
      handle: "@elena_quant",
      avatar: "ER",
      role: "Moderator",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#0F2D1F]",
      joinedDate: "Feb 2025",
    },
    {
      id: "u3",
      name: "Sarah Sterling",
      handle: "@sterling_equities",
      avatar: "SS",
      role: "Top Contributor",
      isOnline: true,
      badgeColor: "bg-[#F3F0E5] text-[#55554E]",
      joinedDate: "Mar 2025",
    },
    {
      id: "u_self",
      name: "Vish Sai",
      handle: "@vish_capitals",
      avatar: "VS",
      role: "Admin",
      isOnline: true,
      badgeColor: "bg-[#0F2D1F] text-white",
      joinedDate: "Founder",
    },
  ],
  "crypto-discussion": [
    {
      id: "u5",
      name: "Kavita Nair",
      handle: "@kavita_crypto",
      avatar: "KN",
      role: "Pro Analyst",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#18794E]",
      joinedDate: "Nov 2024",
    },
    {
      id: "u6",
      name: "Vikram Patel",
      handle: "@vikram_onchain",
      avatar: "VP",
      role: "Moderator",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#0F2D1F]",
      joinedDate: "Dec 2024",
    },
    {
      id: "u_self",
      name: "Vish Sai",
      handle: "@vish_capitals",
      avatar: "VS",
      role: "Admin",
      isOnline: true,
      badgeColor: "bg-[#0F2D1F] text-white",
      joinedDate: "Founder",
    },
  ],
  "stock-market": [
    {
      id: "u3",
      name: "Sarah Sterling",
      handle: "@sterling_equities",
      avatar: "SS",
      role: "Pro Analyst",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#18794E]",
      joinedDate: "Mar 2025",
    },
    {
      id: "u8",
      name: "Alex Rivera",
      handle: "@arivera_sec",
      avatar: "AR",
      role: "Moderator",
      isOnline: true,
      badgeColor: "bg-[#E8F2EA] text-[#0F2D1F]",
      joinedDate: "Apr 2025",
    },
    {
      id: "u_self",
      name: "Vish Sai",
      handle: "@vish_capitals",
      avatar: "VS",
      role: "Admin",
      isOnline: true,
      badgeColor: "bg-[#0F2D1F] text-white",
      joinedDate: "Founder",
    },
  ],
}

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  "general-discussion": [
    {
      id: "m1",
      communityId: "general-discussion",
      senderId: "u2",
      senderName: "Elena Rostova",
      senderAvatar: "ER",
      senderRole: "Moderator",
      content:
        "Welcome to the General Discussion channel. This channel is designated for high-level market thoughts, macroeconomic sentiment, and investment ideas across the Vish Capitals community.",
      timestamp: "09:00 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [
        { emoji: "📈", count: 8, hasReacted: false },
        { emoji: "🤝", count: 5, hasReacted: false },
      ],
      isPinned: true,
    },
  ],
  "crypto-discussion": [
    {
      id: "c1",
      communityId: "crypto-discussion",
      senderId: "u6",
      senderName: "Vikram Patel",
      senderAvatar: "VP",
      senderRole: "Moderator",
      content:
        "Welcome to Crypto Discussion. Use this channel to discuss Bitcoin, Ethereum, layer-1 blockchains, on-chain liquidity, and institutional market structure.",
      timestamp: "09:00 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [{ emoji: "🔥", count: 12, hasReacted: false }],
      isPinned: true,
    },
  ],
  "stock-market": [
    {
      id: "s1",
      communityId: "stock-market",
      senderId: "u8",
      senderName: "Alex Rivera",
      senderAvatar: "AR",
      senderRole: "Moderator",
      content:
        "Welcome to the Stock Market channel. Share equity research, company valuation insights, earnings analysis, and sector rotation setups.",
      timestamp: "09:00 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [{ emoji: "📊", count: 7, hasReacted: false }],
      isPinned: true,
    },
  ],
  "investment-beginners": [
    {
      id: "b1",
      communityId: "investment-beginners",
      senderId: "u2",
      senderName: "Elena Rostova",
      senderAvatar: "ER",
      senderRole: "Moderator",
      content:
        "Welcome to Investment Beginners. This is a supportive space to ask questions about portfolio sizing, paper trading simulation, and market risk fundamentals.",
      timestamp: "09:00 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [{ emoji: "🎓", count: 15, hasReacted: false }],
      isPinned: true,
    },
  ],
  "market-news": [
    {
      id: "n1",
      communityId: "market-news",
      senderId: "u_bot",
      senderName: "NewsDesk Bot",
      senderAvatar: "NB",
      senderRole: "Moderator",
      content:
        "Market News Desk is live. Official verified macroeconomic alerts, rate decisions, and institutional announcements will be posted here.",
      timestamp: "09:00 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [{ emoji: "📰", count: 14, hasReacted: false }],
      isPinned: true,
    },
  ],
  "trading-strategies": [
    {
      id: "t1",
      communityId: "trading-strategies",
      senderId: "u9",
      senderName: "Dr. Henrik Lind",
      senderAvatar: "HL",
      senderRole: "Pro Analyst",
      content:
        "Welcome to Trading Strategies. Share systematic backtests, technical setups, and risk mitigation models.",
      timestamp: "09:00 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [{ emoji: "🧠", count: 9, hasReacted: false }],
      isPinned: true,
    },
  ],
  "portfolio-discussion": [
    {
      id: "p1",
      communityId: "portfolio-discussion",
      senderId: "u10",
      senderName: "Maya Lin",
      senderAvatar: "ML",
      senderRole: "Moderator",
      content:
        "Welcome to Portfolio Discussion. Discuss multi-asset allocation, rebalancing cadence, and risk-adjusted returns.",
      timestamp: "09:00 AM",
      date: "Today",
      isCurrentUser: false,
      reactions: [{ emoji: "💼", count: 11, hasReacted: false }],
      isPinned: true,
    },
  ],
}
