"use client";
import Link from "next/link";
import { ArrowUpRight, CheckCircle2, Circle, ListChecks, Sparkles } from "lucide-react";
import { useMarketSnapshot } from "@/hooks/useMarketSnapshot";
import { useWatchlists } from "@/hooks/useTerminalAccount";
import { useWorkspace } from "./WorkspaceContext";
import { percent } from "@/lib/market-data";
import CoinIcon from "@/components/market/CoinIcon";
export default function SessionBriefing() {
  const market = useMarketSnapshot(), lists = useWatchlists();
  const { activeSymbol, openAhna } = useWorkspace();
  const movers = [...(market.data?.coins ?? [])].filter(c => !["USDT", "USDC"].includes(c.symbol)).sort((a, b) => Math.abs(b.priceChange) - Math.abs(a.priceChange)).slice(0, 3);
  return <section className="cc-card cc-session-briefing"><div className="cc-card-heading"><div className="cc-inline"><span className="cc-icon-tile"><ListChecks size={20}/></span><div><span className="cc-eyebrow">A useful starting point</span><h2>Your session briefing</h2></div></div><span className="cc-status-tag">Before your next move</span></div><div className="cc-session-body"><p className="cc-session-intro">Start with what changed, check the evidence, then review your risk.</p><div className="cc-session-movers"><span className="cc-eyebrow">Largest absolute moves · tracked reference markets</span>{movers.length ? movers.map(coin => <Link href={`/markets?coin=${coin.id}`} key={coin.id}><CoinIcon symbol={coin.symbol} image={coin.image} size={25}/><strong>{coin.symbol}</strong><span className={coin.priceChange < 0 ? "cc-negative" : "cc-positive"}>{percent(coin.priceChange)}</span><ArrowUpRight size={13}/></Link>) : <p className="cc-muted">Movements will appear when the market feed responds.</p>}{market.isError && <small className="cc-negative">Market refresh failed; any movements shown may be delayed.</small>}</div><ol className="cc-session-checklist"><li>{lists.data?.total ? <CheckCircle2 size={16}/> : <Circle size={16}/>}<div><strong>Review your saved markets</strong><p>{lists.isError ? "Watchlist status is unavailable." : lists.data ? `${lists.data.total} saved watchlist${lists.data.total === 1 ? "" : "s"}. Use the watchlist beside this briefing to choose a market.` : "Checking your watchlists…"}</p></div></li><li><Circle size={16}/><div><strong>Read the opposing evidence</strong><p>Compare technical and news sentiment in the individual-agent view.</p><Link href={`/intelligence?symbol=${activeSymbol}`}>Inspect agents<ArrowUpRight size={12}/></Link></div></li><li><Circle size={16}/><div><strong>Plan the downside</strong><p>Review sizing and invalidation in the paper trade planner before any execution.</p><Link href={`/paper-trading?symbol=${activeSymbol}&mode=paper`}>Open paper planner<ArrowUpRight size={12}/></Link></div></li></ol><button type="button" className="cc-session-ask" onClick={openAhna}><Sparkles size={16}/><span>Build a brief with AHNA</span><ArrowUpRight size={15}/></button></div></section>;
}
