"""Add AHNAAnalysis model

Revision ID: 3380d2700d94
Revises: 382688a78e67
Create Date: 2026-08-31 16:44:39.703173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3380d2700d94'
down_revision = '382688a78e67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        inspector = sa.inspect(bind)
        if 'ahna_analyses' not in inspector.get_table_names():
            op.create_table('ahna_analyses',
                sa.Column('id', sa.UUID(), nullable=False),
                sa.Column('user_id', sa.UUID(), nullable=False),
                sa.Column('symbol', sa.String(length=50), nullable=False),
                sa.Column('question', sa.String(length=500), nullable=True),
                sa.Column('market_data', sa.JSON(), nullable=True),
                sa.Column('news_data', sa.JSON(), nullable=True),
                sa.Column('sentiment_data', sa.JSON(), nullable=True),
                sa.Column('feature_data', sa.JSON(), nullable=True),
                sa.Column('risk_data', sa.JSON(), nullable=True),
                sa.Column('trade_data', sa.JSON(), nullable=True),
                sa.Column('ai_response', sa.JSON(), nullable=True),
                sa.Column('decision', sa.String(length=50), nullable=True),
                sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
                sa.Column('model_version', sa.String(length=100), nullable=True),
                sa.Column('created_at', sa.DateTime(), nullable=False),
                sa.PrimaryKeyConstraint('id')
            )
            op.create_index(op.f('ix_ahna_analyses_symbol'), 'ahna_analyses', ['symbol'], unique=False)
            op.create_index('ix_ahna_analyses_symbol_created_at', 'ahna_analyses', ['symbol', 'created_at'], unique=False)
            op.create_index(op.f('ix_ahna_analyses_user_id'), 'ahna_analyses', ['user_id'], unique=False)
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ahna_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=True),
    sa.Column('market_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('news_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trade_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ahna_analyses_symbol'), 'ahna_analyses', ['symbol'], unique=False)
    op.create_index('ix_ahna_analyses_symbol_created_at', 'ahna_analyses', ['symbol', 'created_at'], unique=False)
    op.create_index(op.f('ix_ahna_analyses_user_id'), 'ahna_analyses', ['user_id'], unique=False)
    op.alter_column('ai_agent_runs', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ai_agent_runs', 'request_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('idx_ai_agent_runs_agent_name', table_name='ai_agent_runs')
    op.drop_index('idx_ai_agent_runs_user_id', table_name='ai_agent_runs')
    op.drop_index('ix_ai_agent_runs_request_id', table_name='ai_agent_runs')
    op.create_index('ix_ai_agent_runs_status', 'ai_agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_agent_runs_user_id'), 'ai_agent_runs', ['user_id'], unique=False)
    op.drop_constraint('ai_agent_runs_user_id_fkey', 'ai_agent_runs', type_='foreignkey')
    op.alter_column('ai_conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('idx_ai_conversations_user_id', table_name='ai_conversations')
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.drop_constraint('ai_conversations_context_asset_id_fkey', 'ai_conversations', type_='foreignkey')
    op.drop_constraint('ai_conversations_user_id_fkey', 'ai_conversations', type_='foreignkey')
    op.add_column('ai_insights', sa.Column('source', sa.String(length=100), nullable=True))
    op.alter_column('ai_insights', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.drop_index('idx_ai_insights_asset_id', table_name='ai_insights')
    op.drop_index('idx_ai_insights_user_id', table_name='ai_insights')
    op.create_index('ix_ai_insights_asset_id', 'ai_insights', ['asset_id'], unique=False)
    op.create_index('ix_ai_insights_generated_at', 'ai_insights', ['generated_at'], unique=False)
    op.create_index(op.f('ix_ai_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    op.drop_constraint('ai_insights_user_id_fkey', 'ai_insights', type_='foreignkey')
    op.drop_constraint('ai_insights_asset_id_fkey', 'ai_insights', type_='foreignkey')
    op.drop_column('ai_insights', 'source_metadata')
    op.drop_index('idx_ai_messages_conversation_id', table_name='ai_messages')
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.drop_constraint('ai_messages_conversation_id_fkey', 'ai_messages', type_='foreignkey')
    op.add_column('alert_events', sa.Column('notified', sa.Boolean(), nullable=True))
    op.alter_column('alert_events', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('idx_alert_events_alert_rule_id', table_name='alert_events')
    op.drop_index('idx_alert_events_triggered_at', table_name='alert_events')
    op.create_index(op.f('ix_alert_events_alert_rule_id'), 'alert_events', ['alert_rule_id'], unique=False)
    op.create_index('ix_alert_events_triggered_at', 'alert_events', ['triggered_at'], unique=False)
    op.drop_constraint('alert_events_alert_rule_id_fkey', 'alert_events', type_='foreignkey')
    op.drop_column('alert_events', 'notification_sent')
    op.add_column('alert_rules', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.add_column('alert_rules', sa.Column('cooldown_minutes', sa.Numeric(precision=10, scale=0), nullable=True))
    op.alter_column('alert_rules', 'threshold',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.drop_index('idx_alert_rules_user_id', table_name='alert_rules')
    op.create_index('ix_alert_rules_asset_id', 'alert_rules', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.drop_constraint('alert_rules_user_id_fkey', 'alert_rules', type_='foreignkey')
    op.drop_constraint('alert_rules_asset_id_fkey', 'alert_rules', type_='foreignkey')
    op.drop_column('alert_rules', 'is_enabled')
    op.drop_column('alert_rules', 'cooldown_seconds')
    op.alter_column('assets', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('assets', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('ix_assets_status', 'assets', ['status'], unique=False)
    op.create_unique_constraint('uq_assets_exchange_pair', 'assets', ['exchange', 'base_asset', 'quote_asset'])
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_request_id', table_name='audit_logs')
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_constraint('community_bookmarks_user_id_post_id_key', 'community_bookmarks', type_='unique')
    op.drop_index('idx_community_bookmarks_user_id', table_name='community_bookmarks')
    op.create_unique_constraint('uq_community_bookmarks', 'community_bookmarks', ['user_id', 'post_id'])
    op.drop_constraint('community_bookmarks_user_id_fkey', 'community_bookmarks', type_='foreignkey')
    op.drop_constraint('community_bookmarks_post_id_fkey', 'community_bookmarks', type_='foreignkey')
    op.drop_index('idx_community_comments_post_id', table_name='community_comments')
    op.drop_index('idx_community_comments_user_id', table_name='community_comments')
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_index('ix_community_comments_user_id', 'community_comments', ['user_id'], unique=False)
    op.drop_constraint('community_comments_user_id_fkey', 'community_comments', type_='foreignkey')
    op.drop_constraint('community_comments_post_id_fkey', 'community_comments', type_='foreignkey')
    op.drop_constraint('community_follows_follower_id_following_id_key', 'community_follows', type_='unique')
    op.drop_index('idx_community_follows_follower_id', table_name='community_follows')
    op.drop_index('idx_community_follows_following_id', table_name='community_follows')
    op.create_index('ix_community_follows_following_id', 'community_follows', ['following_id'], unique=False)
    op.create_unique_constraint('uq_community_follows', 'community_follows', ['follower_id', 'following_id'])
    op.drop_constraint('community_follows_follower_id_fkey', 'community_follows', type_='foreignkey')
    op.drop_constraint('community_follows_following_id_fkey', 'community_follows', type_='foreignkey')
    op.add_column('community_likes', sa.Column('post_id', sa.UUID(), nullable=True))
    op.add_column('community_likes', sa.Column('comment_id', sa.UUID(), nullable=True))
    op.drop_constraint('community_likes_user_id_target_type_target_id_key', 'community_likes', type_='unique')
    op.drop_index('idx_community_likes_user_id', table_name='community_likes')
    op.create_index('ix_community_likes_post_id', 'community_likes', ['post_id'], unique=False)
    op.create_unique_constraint('uq_community_likes', 'community_likes', ['user_id', 'target_type', 'target_id'])
    op.drop_constraint('community_likes_user_id_fkey', 'community_likes', type_='foreignkey')
    op.alter_column('community_posts', 'visibility',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('idx_community_posts_created_at', table_name='community_posts')
    op.drop_index('idx_community_posts_user_id', table_name='community_posts')
    op.create_index('ix_community_posts_created_at', 'community_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_user_id'), 'community_posts', ['user_id'], unique=False)
    op.drop_constraint('community_posts_user_id_fkey', 'community_posts', type_='foreignkey')
    op.add_column('community_reports', sa.Column('post_id', sa.UUID(), nullable=True))
    op.add_column('community_reports', sa.Column('comment_id', sa.UUID(), nullable=True))
    op.alter_column('community_reports', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('idx_community_reports_reporter_id', table_name='community_reports')
    op.drop_index('idx_community_reports_status', table_name='community_reports')
    op.create_index('ix_community_reports_reporter_id', 'community_reports', ['reporter_id'], unique=False)
    op.create_index('ix_community_reports_status', 'community_reports', ['status'], unique=False)
    op.drop_constraint('community_reports_reporter_id_fkey', 'community_reports', type_='foreignkey')
    op.drop_column('community_reports', 'description')
    op.drop_column('community_reports', 'target_id')
    op.drop_column('community_reports', 'updated_at')
    op.drop_column('community_reports', 'target_type')
    op.alter_column('markets', 'symbol',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_user_read', table_name='notifications')
    op.create_index('ix_notifications_read_at', 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.alter_column('paper_accounts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('paper_accounts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('idx_paper_accounts_user_id', table_name='paper_accounts')
    op.drop_constraint('uq_paper_accounts_user_id', 'paper_accounts', type_='unique')
    op.create_index(op.f('ix_paper_accounts_user_id'), 'paper_accounts', ['user_id'], unique=True)
    op.alter_column('paper_orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('paper_orders', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index('idx_paper_orders_paper_account_id', table_name='paper_orders')
    op.drop_index('idx_paper_orders_status', table_name='paper_orders')
    op.drop_index('idx_paper_orders_user_id', table_name='paper_orders')
    op.create_index('ix_paper_orders_asset_id', 'paper_orders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_paper_account_id'), 'paper_orders', ['paper_account_id'], unique=False)
    op.create_index('ix_paper_orders_status', 'paper_orders', ['status'], unique=False)
    op.create_index(op.f('ix_paper_orders_user_id'), 'paper_orders', ['user_id'], unique=False)
    op.drop_constraint('paper_orders_paper_account_id_fkey', 'paper_orders', type_='foreignkey')
    op.drop_constraint('paper_orders_asset_id_fkey', 'paper_orders', type_='foreignkey')
    op.alter_column('paper_positions', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.alter_column('paper_positions', 'unrealized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.drop_index('idx_paper_positions_paper_account_id', table_name='paper_positions')
    op.drop_index('idx_paper_positions_user_id', table_name='paper_positions')
    op.drop_constraint('paper_positions_paper_account_id_asset_id_key', 'paper_positions', type_='unique')
    op.create_index('ix_paper_positions_asset_id', 'paper_positions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_paper_account_id'), 'paper_positions', ['paper_account_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_user_id'), 'paper_positions', ['user_id'], unique=False)
    op.create_unique_constraint('uq_paper_positions_account_asset', 'paper_positions', ['paper_account_id', 'asset_id'])
    op.drop_constraint('paper_positions_paper_account_id_fkey', 'paper_positions', type_='foreignkey')
    op.drop_constraint('paper_positions_asset_id_fkey', 'paper_positions', type_='foreignkey')
    op.alter_column('paper_trades', 'fee',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.alter_column('paper_trades', 'slippage',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.alter_column('paper_trades', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.drop_index('idx_paper_trades_executed_at', table_name='paper_trades')
    op.drop_index('idx_paper_trades_paper_account_id', table_name='paper_trades')
    op.drop_index('idx_paper_trades_user_id', table_name='paper_trades')
    op.create_index('ix_paper_trades_asset_id', 'paper_trades', ['asset_id'], unique=False)
    op.create_index('ix_paper_trades_executed_at', 'paper_trades', ['executed_at'], unique=False)
    op.create_index(op.f('ix_paper_trades_paper_account_id'), 'paper_trades', ['paper_account_id'], unique=False)
    op.create_index(op.f('ix_paper_trades_user_id'), 'paper_trades', ['user_id'], unique=False)
    op.drop_constraint('paper_trades_order_id_fkey', 'paper_trades', type_='foreignkey')
    op.drop_constraint('paper_trades_paper_account_id_fkey', 'paper_trades', type_='foreignkey')
    op.drop_constraint('paper_trades_asset_id_fkey', 'paper_trades', type_='foreignkey')
    op.drop_index('idx_paper_transactions_paper_account_id', table_name='paper_transactions')
    op.drop_index('idx_paper_transactions_user_id', table_name='paper_transactions')
    op.create_index(op.f('ix_paper_transactions_paper_account_id'), 'paper_transactions', ['paper_account_id'], unique=False)
    op.create_index(op.f('ix_paper_transactions_user_id'), 'paper_transactions', ['user_id'], unique=False)
    op.drop_constraint('paper_transactions_paper_account_id_fkey', 'paper_transactions', type_='foreignkey')
    op.add_column('plan_entitlements', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('plan_entitlements', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_constraint('plan_entitlements_plan_id_entitlement_code_key', 'plan_entitlements', type_='unique')
    op.create_index(op.f('ix_plan_entitlements_plan_id'), 'plan_entitlements', ['plan_id'], unique=False)
    op.create_unique_constraint('uq_plan_entitlements', 'plan_entitlements', ['plan_id', 'entitlement_code'])
    op.drop_constraint('plan_entitlements_plan_id_fkey', 'plan_entitlements', type_='foreignkey')
    op.alter_column('portfolio_snapshots', 'paper_account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('portfolio_snapshots', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.alter_column('portfolio_snapshots', 'unrealized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.alter_column('portfolio_snapshots', 'drawdown',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.drop_index('idx_portfolio_snapshots_recorded_at', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_snapshots_user_id', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_snapshots_user_recorded', table_name='portfolio_snapshots')
    op.create_index('ix_portfolio_snapshots_recorded_at', 'portfolio_snapshots', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_user_id'), 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_index('ix_portfolio_snapshots_user_recorded', 'portfolio_snapshots', ['user_id', 'recorded_at'], unique=False)
    op.drop_constraint('portfolio_snapshots_paper_account_id_fkey', 'portfolio_snapshots', type_='foreignkey')
    op.drop_constraint('portfolio_snapshots_user_id_fkey', 'portfolio_snapshots', type_='foreignkey')
    op.alter_column('subscription_plans', 'billing_interval',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('subscription_plans', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.create_index('ix_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_constraint('subscriptions_plan_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_index('idx_trade_journal_entries_user_id', table_name='trade_journal_entries')
    op.create_index(op.f('ix_trade_journal_entries_user_id'), 'trade_journal_entries', ['user_id'], unique=False)
    op.drop_constraint('trade_journal_entries_user_id_fkey', 'trade_journal_entries', type_='foreignkey')
    op.drop_constraint('trade_journal_entries_paper_trade_id_fkey', 'trade_journal_entries', type_='foreignkey')
    op.add_column('tutor_courses', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.drop_column('tutor_courses', 'is_active')
    op.drop_column('tutor_courses', 'duration_minutes')
    op.drop_column('tutor_courses', 'level')
    op.add_column('tutor_lessons', sa.Column('order_num', sa.Integer(), nullable=True))
    op.drop_index('idx_tutor_lessons_course_id', table_name='tutor_lessons')
    op.create_index(op.f('ix_tutor_lessons_course_id'), 'tutor_lessons', ['course_id'], unique=False)
    op.drop_constraint('tutor_lessons_course_id_fkey', 'tutor_lessons', type_='foreignkey')
    op.drop_column('tutor_lessons', 'description')
    op.drop_column('tutor_lessons', 'position')
    op.drop_column('tutor_lessons', 'updated_at')
    op.drop_column('tutor_lessons', 'duration_minutes')
    op.add_column('tutor_progress', sa.Column('lessons_completed', sa.Integer(), nullable=True))
    op.add_column('tutor_progress', sa.Column('completion_percent', sa.Integer(), nullable=True))
    op.alter_column('tutor_progress', 'total_lessons',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_tutor_progress_user_id', table_name='tutor_progress')
    op.drop_constraint('tutor_progress_user_id_course_id_key', 'tutor_progress', type_='unique')
    op.create_index(op.f('ix_tutor_progress_user_id'), 'tutor_progress', ['user_id'], unique=False)
    op.create_unique_constraint('uq_tutor_progress_user_course', 'tutor_progress', ['user_id', 'course_id'])
    op.drop_constraint('tutor_progress_course_id_fkey', 'tutor_progress', type_='foreignkey')
    op.drop_constraint('tutor_progress_user_id_fkey', 'tutor_progress', type_='foreignkey')
    op.drop_column('tutor_progress', 'completed_at')
    op.drop_column('tutor_progress', 'quiz_score')
    op.drop_column('tutor_progress', 'progress_percentage')
    op.drop_column('tutor_progress', 'completed_lessons')
    op.add_column('tutor_questions', sa.Column('question', sa.Text(), nullable=False))
    op.alter_column('tutor_questions', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('idx_tutor_questions_lesson_id', table_name='tutor_questions')
    op.create_index(op.f('ix_tutor_questions_lesson_id'), 'tutor_questions', ['lesson_id'], unique=False)
    op.drop_constraint('tutor_questions_lesson_id_fkey', 'tutor_questions', type_='foreignkey')
    op.drop_column('tutor_questions', 'explanation')
    op.drop_column('tutor_questions', 'position')
    op.drop_column('tutor_questions', 'question_type')
    op.drop_column('tutor_questions', 'updated_at')
    op.drop_column('tutor_questions', 'question_text')
    op.add_column('tutor_quiz_attempts', sa.Column('attempt_num', sa.Integer(), nullable=True))
    op.add_column('tutor_quiz_attempts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('tutor_quiz_attempts', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tutor_quiz_attempts', 'passed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tutor_quiz_attempts', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('idx_tutor_quiz_attempts_quiz_id', table_name='tutor_quiz_attempts')
    op.drop_index('idx_tutor_quiz_attempts_user_id', table_name='tutor_quiz_attempts')
    op.create_index('ix_tutor_quiz_attempts_quiz_id', 'tutor_quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_tutor_quiz_attempts_user_id'), 'tutor_quiz_attempts', ['user_id'], unique=False)
    op.drop_constraint('tutor_quiz_attempts_quiz_id_fkey', 'tutor_quiz_attempts', type_='foreignkey')
    op.drop_constraint('tutor_quiz_attempts_user_id_fkey', 'tutor_quiz_attempts', type_='foreignkey')
    op.drop_column('tutor_quiz_attempts', 'started_at')
    op.drop_column('tutor_quiz_attempts', 'answers')
    op.alter_column('tutor_quizzes', 'passing_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_tutor_quizzes_course_id', table_name='tutor_quizzes')
    op.create_index(op.f('ix_tutor_quizzes_course_id'), 'tutor_quizzes', ['course_id'], unique=False)
    op.drop_constraint('tutor_quizzes_course_id_fkey', 'tutor_quizzes', type_='foreignkey')
    op.drop_column('tutor_quizzes', 'is_active')
    op.drop_column('tutor_quizzes', 'updated_at')
    op.drop_column('tutor_quizzes', 'description')
    op.alter_column('user_preferences', 'theme_preference',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'light'::character varying"))
    op.drop_constraint('user_preferences_user_id_key', 'user_preferences', type_='unique')
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.drop_column('user_preferences', 'timezone')
    op.drop_constraint('user_profiles_user_id_key', 'user_profiles', type_='unique')
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_profiles_user_id', 'user_profiles', ['user_id'])
    op.alter_column('user_sessions', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('idx_user_sessions_expires_at', table_name='user_sessions')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('ix_user_sessions_session_hash', table_name='user_sessions')
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_revoked_at', 'user_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'user_sessions', ['session_hash'])
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.alter_column('watchlist_items', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_watchlist_items_watchlist_id', table_name='watchlist_items')
    op.drop_constraint('watchlist_items_watchlist_id_asset_id_key', 'watchlist_items', type_='unique')
    op.create_index('ix_watchlist_items_asset_id', 'watchlist_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_unique_constraint('uq_watchlist_items', 'watchlist_items', ['watchlist_id', 'asset_id'])
    op.drop_constraint('watchlist_items_watchlist_id_fkey', 'watchlist_items', type_='foreignkey')
    op.drop_constraint('watchlist_items_asset_id_fkey', 'watchlist_items', type_='foreignkey')
    op.drop_index('idx_watchlists_user_id', table_name='watchlists')
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.drop_constraint('watchlists_user_id_fkey', 'watchlists', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('watchlists_user_id_fkey', 'watchlists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.create_index('idx_watchlists_user_id', 'watchlists', ['user_id'], unique=False)
    op.create_foreign_key('watchlist_items_asset_id_fkey', 'watchlist_items', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('watchlist_items_watchlist_id_fkey', 'watchlist_items', 'watchlists', ['watchlist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_watchlist_items', 'watchlist_items', type_='unique')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_index('ix_watchlist_items_asset_id', table_name='watchlist_items')
    op.create_unique_constraint('watchlist_items_watchlist_id_asset_id_key', 'watchlist_items', ['watchlist_id', 'asset_id'])
    op.create_index('idx_watchlist_items_watchlist_id', 'watchlist_items', ['watchlist_id'], unique=False)
    op.alter_column('watchlist_items', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_users_created_at', table_name='users')
    op.alter_column('users', 'is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_revoked_at', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.create_index('ix_user_sessions_session_hash', 'user_sessions', ['session_hash'], unique=False)
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('idx_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.alter_column('user_sessions', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('uq_user_profiles_user_id', 'user_profiles', type_='unique')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.create_unique_constraint('user_profiles_user_id_key', 'user_profiles', ['user_id'])
    op.add_column('user_preferences', sa.Column('timezone', sa.VARCHAR(length=63), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.create_unique_constraint('user_preferences_user_id_key', 'user_preferences', ['user_id'])
    op.alter_column('user_preferences', 'theme_preference',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'light'::character varying"))
    op.add_column('tutor_quizzes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tutor_quizzes', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('tutor_quizzes', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_foreign_key('tutor_quizzes_course_id_fkey', 'tutor_quizzes', 'tutor_courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tutor_quizzes_course_id'), table_name='tutor_quizzes')
    op.create_index('idx_tutor_quizzes_course_id', 'tutor_quizzes', ['course_id'], unique=False)
    op.alter_column('tutor_quizzes', 'passing_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('tutor_quiz_attempts', sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tutor_quiz_attempts', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key('tutor_quiz_attempts_user_id_fkey', 'tutor_quiz_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tutor_quiz_attempts_quiz_id_fkey', 'tutor_quiz_attempts', 'tutor_quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tutor_quiz_attempts_user_id'), table_name='tutor_quiz_attempts')
    op.drop_index('ix_tutor_quiz_attempts_quiz_id', table_name='tutor_quiz_attempts')
    op.create_index('idx_tutor_quiz_attempts_user_id', 'tutor_quiz_attempts', ['user_id'], unique=False)
    op.create_index('idx_tutor_quiz_attempts_quiz_id', 'tutor_quiz_attempts', ['quiz_id'], unique=False)
    op.alter_column('tutor_quiz_attempts', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tutor_quiz_attempts', 'passed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tutor_quiz_attempts', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tutor_quiz_attempts', 'created_at')
    op.drop_column('tutor_quiz_attempts', 'attempt_num')
    op.add_column('tutor_questions', sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('tutor_questions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('tutor_questions', sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('tutor_questions', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tutor_questions', sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('tutor_questions_lesson_id_fkey', 'tutor_questions', 'tutor_lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tutor_questions_lesson_id'), table_name='tutor_questions')
    op.create_index('idx_tutor_questions_lesson_id', 'tutor_questions', ['lesson_id'], unique=False)
    op.alter_column('tutor_questions', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('tutor_questions', 'question')
    op.add_column('tutor_progress', sa.Column('completed_lessons', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('tutor_progress', sa.Column('progress_percentage', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tutor_progress', sa.Column('quiz_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tutor_progress', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('tutor_progress_user_id_fkey', 'tutor_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tutor_progress_course_id_fkey', 'tutor_progress', 'tutor_courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_tutor_progress_user_course', 'tutor_progress', type_='unique')
    op.drop_index(op.f('ix_tutor_progress_user_id'), table_name='tutor_progress')
    op.create_unique_constraint('tutor_progress_user_id_course_id_key', 'tutor_progress', ['user_id', 'course_id'])
    op.create_index('idx_tutor_progress_user_id', 'tutor_progress', ['user_id'], unique=False)
    op.alter_column('tutor_progress', 'total_lessons',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tutor_progress', 'completion_percent')
    op.drop_column('tutor_progress', 'lessons_completed')
    op.add_column('tutor_lessons', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tutor_lessons', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('tutor_lessons', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tutor_lessons', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('tutor_lessons_course_id_fkey', 'tutor_lessons', 'tutor_courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tutor_lessons_course_id'), table_name='tutor_lessons')
    op.create_index('idx_tutor_lessons_course_id', 'tutor_lessons', ['course_id'], unique=False)
    op.drop_column('tutor_lessons', 'order_num')
    op.add_column('tutor_courses', sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('tutor_courses', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tutor_courses', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('tutor_courses', 'difficulty')
    op.create_foreign_key('trade_journal_entries_paper_trade_id_fkey', 'trade_journal_entries', 'paper_trades', ['paper_trade_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('trade_journal_entries_user_id_fkey', 'trade_journal_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_trade_journal_entries_user_id'), table_name='trade_journal_entries')
    op.create_index('idx_trade_journal_entries_user_id', 'trade_journal_entries', ['user_id'], unique=False)
    op.create_foreign_key('subscriptions_user_id_fkey', 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subscriptions_plan_id_fkey', 'subscriptions', 'subscription_plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_plan_id', table_name='subscriptions')
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('subscription_plans', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('subscription_plans', 'billing_interval',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key('portfolio_snapshots_user_id_fkey', 'portfolio_snapshots', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('portfolio_snapshots_paper_account_id_fkey', 'portfolio_snapshots', 'paper_accounts', ['paper_account_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_portfolio_snapshots_user_recorded', table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_user_id'), table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_recorded_at', table_name='portfolio_snapshots')
    op.create_index('idx_portfolio_snapshots_user_recorded', 'portfolio_snapshots', ['user_id', 'recorded_at'], unique=False)
    op.create_index('idx_portfolio_snapshots_user_id', 'portfolio_snapshots', ['user_id'], unique=False)
    op.create_index('idx_portfolio_snapshots_recorded_at', 'portfolio_snapshots', ['recorded_at'], unique=False)
    op.alter_column('portfolio_snapshots', 'drawdown',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.alter_column('portfolio_snapshots', 'unrealized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.alter_column('portfolio_snapshots', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.alter_column('portfolio_snapshots', 'paper_account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key('plan_entitlements_plan_id_fkey', 'plan_entitlements', 'subscription_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_plan_entitlements', 'plan_entitlements', type_='unique')
    op.drop_index(op.f('ix_plan_entitlements_plan_id'), table_name='plan_entitlements')
    op.create_unique_constraint('plan_entitlements_plan_id_entitlement_code_key', 'plan_entitlements', ['plan_id', 'entitlement_code'])
    op.drop_column('plan_entitlements', 'description')
    op.drop_column('plan_entitlements', 'name')
    op.create_foreign_key('paper_transactions_paper_account_id_fkey', 'paper_transactions', 'paper_accounts', ['paper_account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_paper_transactions_user_id'), table_name='paper_transactions')
    op.drop_index(op.f('ix_paper_transactions_paper_account_id'), table_name='paper_transactions')
    op.create_index('idx_paper_transactions_user_id', 'paper_transactions', ['user_id'], unique=False)
    op.create_index('idx_paper_transactions_paper_account_id', 'paper_transactions', ['paper_account_id'], unique=False)
    op.create_foreign_key('paper_trades_asset_id_fkey', 'paper_trades', 'assets', ['asset_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('paper_trades_paper_account_id_fkey', 'paper_trades', 'paper_accounts', ['paper_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('paper_trades_order_id_fkey', 'paper_trades', 'paper_orders', ['order_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_paper_trades_user_id'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_paper_account_id'), table_name='paper_trades')
    op.drop_index('ix_paper_trades_executed_at', table_name='paper_trades')
    op.drop_index('ix_paper_trades_asset_id', table_name='paper_trades')
    op.create_index('idx_paper_trades_user_id', 'paper_trades', ['user_id'], unique=False)
    op.create_index('idx_paper_trades_paper_account_id', 'paper_trades', ['paper_account_id'], unique=False)
    op.create_index('idx_paper_trades_executed_at', 'paper_trades', ['executed_at'], unique=False)
    op.alter_column('paper_trades', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.alter_column('paper_trades', 'slippage',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.alter_column('paper_trades', 'fee',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.create_foreign_key('paper_positions_asset_id_fkey', 'paper_positions', 'assets', ['asset_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('paper_positions_paper_account_id_fkey', 'paper_positions', 'paper_accounts', ['paper_account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_paper_positions_account_asset', 'paper_positions', type_='unique')
    op.drop_index(op.f('ix_paper_positions_user_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_paper_account_id'), table_name='paper_positions')
    op.drop_index('ix_paper_positions_asset_id', table_name='paper_positions')
    op.create_unique_constraint('paper_positions_paper_account_id_asset_id_key', 'paper_positions', ['paper_account_id', 'asset_id'])
    op.create_index('idx_paper_positions_user_id', 'paper_positions', ['user_id'], unique=False)
    op.create_index('idx_paper_positions_paper_account_id', 'paper_positions', ['paper_account_id'], unique=False)
    op.alter_column('paper_positions', 'unrealized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.alter_column('paper_positions', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.create_foreign_key('paper_orders_asset_id_fkey', 'paper_orders', 'assets', ['asset_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('paper_orders_paper_account_id_fkey', 'paper_orders', 'paper_accounts', ['paper_account_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_paper_orders_user_id'), table_name='paper_orders')
    op.drop_index('ix_paper_orders_status', table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_paper_account_id'), table_name='paper_orders')
    op.drop_index('ix_paper_orders_asset_id', table_name='paper_orders')
    op.create_index('idx_paper_orders_user_id', 'paper_orders', ['user_id'], unique=False)
    op.create_index('idx_paper_orders_status', 'paper_orders', ['status'], unique=False)
    op.create_index('idx_paper_orders_paper_account_id', 'paper_orders', ['paper_account_id'], unique=False)
    op.alter_column('paper_orders', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('paper_orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_paper_accounts_user_id'), table_name='paper_accounts')
    op.create_unique_constraint('uq_paper_accounts_user_id', 'paper_accounts', ['user_id'])
    op.create_index('idx_paper_accounts_user_id', 'paper_accounts', ['user_id'], unique=False)
    op.alter_column('paper_accounts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('paper_accounts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_read_at', table_name='notifications')
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.alter_column('markets', 'symbol',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('community_reports', sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('community_reports', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('community_reports', sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('community_reports', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('community_reports_reporter_id_fkey', 'community_reports', 'users', ['reporter_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_community_reports_status', table_name='community_reports')
    op.drop_index('ix_community_reports_reporter_id', table_name='community_reports')
    op.create_index('idx_community_reports_status', 'community_reports', ['status'], unique=False)
    op.create_index('idx_community_reports_reporter_id', 'community_reports', ['reporter_id'], unique=False)
    op.alter_column('community_reports', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('community_reports', 'comment_id')
    op.drop_column('community_reports', 'post_id')
    op.create_foreign_key('community_posts_user_id_fkey', 'community_posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_community_posts_user_id'), table_name='community_posts')
    op.drop_index('ix_community_posts_created_at', table_name='community_posts')
    op.create_index('idx_community_posts_user_id', 'community_posts', ['user_id'], unique=False)
    op.create_index('idx_community_posts_created_at', 'community_posts', ['created_at'], unique=False)
    op.alter_column('community_posts', 'visibility',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key('community_likes_user_id_fkey', 'community_likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_community_likes', 'community_likes', type_='unique')
    op.drop_index('ix_community_likes_post_id', table_name='community_likes')
    op.create_index('idx_community_likes_user_id', 'community_likes', ['user_id'], unique=False)
    op.create_unique_constraint('community_likes_user_id_target_type_target_id_key', 'community_likes', ['user_id', 'target_type', 'target_id'])
    op.drop_column('community_likes', 'comment_id')
    op.drop_column('community_likes', 'post_id')
    op.create_foreign_key('community_follows_following_id_fkey', 'community_follows', 'users', ['following_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('community_follows_follower_id_fkey', 'community_follows', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_community_follows', 'community_follows', type_='unique')
    op.drop_index('ix_community_follows_following_id', table_name='community_follows')
    op.create_index('idx_community_follows_following_id', 'community_follows', ['following_id'], unique=False)
    op.create_index('idx_community_follows_follower_id', 'community_follows', ['follower_id'], unique=False)
    op.create_unique_constraint('community_follows_follower_id_following_id_key', 'community_follows', ['follower_id', 'following_id'])
    op.create_foreign_key('community_comments_post_id_fkey', 'community_comments', 'community_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('community_comments_user_id_fkey', 'community_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_community_comments_user_id', table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='community_comments')
    op.create_index('idx_community_comments_user_id', 'community_comments', ['user_id'], unique=False)
    op.create_index('idx_community_comments_post_id', 'community_comments', ['post_id'], unique=False)
    op.create_foreign_key('community_bookmarks_post_id_fkey', 'community_bookmarks', 'community_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('community_bookmarks_user_id_fkey', 'community_bookmarks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_community_bookmarks', 'community_bookmarks', type_='unique')
    op.create_index('idx_community_bookmarks_user_id', 'community_bookmarks', ['user_id'], unique=False)
    op.create_unique_constraint('community_bookmarks_user_id_post_id_key', 'community_bookmarks', ['user_id', 'post_id'])
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'request_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint('uq_assets_exchange_pair', 'assets', type_='unique')
    op.drop_index('ix_assets_status', table_name='assets')
    op.alter_column('assets', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('assets', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('alert_rules', sa.Column('cooldown_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('alert_rules', sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_foreign_key('alert_rules_asset_id_fkey', 'alert_rules', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('alert_rules_user_id_fkey', 'alert_rules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_index('ix_alert_rules_asset_id', table_name='alert_rules')
    op.create_index('idx_alert_rules_user_id', 'alert_rules', ['user_id'], unique=False)
    op.alter_column('alert_rules', 'threshold',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.drop_column('alert_rules', 'cooldown_minutes')
    op.drop_column('alert_rules', 'enabled')
    op.add_column('alert_events', sa.Column('notification_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key('alert_events_alert_rule_id_fkey', 'alert_events', 'alert_rules', ['alert_rule_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_alert_events_triggered_at', table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_rule_id'), table_name='alert_events')
    op.create_index('idx_alert_events_triggered_at', 'alert_events', ['triggered_at'], unique=False)
    op.create_index('idx_alert_events_alert_rule_id', 'alert_events', ['alert_rule_id'], unique=False)
    op.alter_column('alert_events', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('alert_events', 'notified')
    op.create_foreign_key('ai_messages_conversation_id_fkey', 'ai_messages', 'ai_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.create_index('idx_ai_messages_conversation_id', 'ai_messages', ['conversation_id'], unique=False)
    op.add_column('ai_insights', sa.Column('source_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key('ai_insights_asset_id_fkey', 'ai_insights', 'assets', ['asset_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('ai_insights_user_id_fkey', 'ai_insights', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_insights_user_id'), table_name='ai_insights')
    op.drop_index('ix_ai_insights_generated_at', table_name='ai_insights')
    op.drop_index('ix_ai_insights_asset_id', table_name='ai_insights')
    op.create_index('idx_ai_insights_user_id', 'ai_insights', ['user_id'], unique=False)
    op.create_index('idx_ai_insights_asset_id', 'ai_insights', ['asset_id'], unique=False)
    op.alter_column('ai_insights', 'confidence',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.drop_column('ai_insights', 'source')
    op.create_foreign_key('ai_conversations_user_id_fkey', 'ai_conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('ai_conversations_context_asset_id_fkey', 'ai_conversations', 'assets', ['context_asset_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.create_index('idx_ai_conversations_user_id', 'ai_conversations', ['user_id'], unique=False)
    op.alter_column('ai_conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key('ai_agent_runs_user_id_fkey', 'ai_agent_runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_agent_runs_user_id'), table_name='ai_agent_runs')
    op.drop_index('ix_ai_agent_runs_status', table_name='ai_agent_runs')
    op.create_index('ix_ai_agent_runs_request_id', 'ai_agent_runs', ['request_id'], unique=False)
    op.create_index('idx_ai_agent_runs_user_id', 'ai_agent_runs', ['user_id'], unique=False)
    op.create_index('idx_ai_agent_runs_agent_name', 'ai_agent_runs', ['agent_name'], unique=False)
    op.alter_column('ai_agent_runs', 'request_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ai_agent_runs', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_ahna_analyses_user_id'), table_name='ahna_analyses')
    op.drop_index('ix_ahna_analyses_symbol_created_at', table_name='ahna_analyses')
    op.drop_index(op.f('ix_ahna_analyses_symbol'), table_name='ahna_analyses')
    op.drop_table('ahna_analyses')
    # ### end Alembic commands ###
